package final_project;


import final_project.HOME_PAGE;
import javax.swing.JOptionPane;
import final_project.FILE_MANAGER;
//import final_project.FILE_MANAGER.FileManager;
import java.io.IOException;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class DELETING_EMPLOYEE extends javax.swing.JPanel {
                  

    /**
     * Creates new form DELETING_EMPLOYEE
     */
    public DELETING_EMPLOYEE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        GiveLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(0, 11, 120, 23);

        GiveLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GiveLabel.setForeground(new java.awt.Color(255, 102, 102));
        GiveLabel.setText("Give the employee ID of the employee whom you want to delete");
        add(GiveLabel);
        GiveLabel.setBounds(420, 66, 560, 36);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        add(idField);
        idField.setBounds(420, 108, 236, 45);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        add(okButton);
        okButton.setBounds(420, 184, 130, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1180, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        HOME_PAGE.home.remove(this);
        HOME_PAGE.home.setContentPane(HOME_PAGE.panel);
        HOME_PAGE.panel.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
         String str=idField.getText();
         if(str.equals(""))JOptionPane.showMessageDialog(null,"You have not entered any employee Id","Warning",0);
         else
         try{
          FileManager fm=new FileManager("EMPLOYEE_LIST.txt");
          int x=Integer.parseInt(str);
          if(fm.search(x)==-1){JOptionPane.showMessageDialog(null,"This id does not exist","Error",2);}
          else{
              int choice=JOptionPane.showConfirmDialog(null,"Are you sure to remove this employee with User Id :"+idField.getText(),"Select option",JOptionPane.YES_NO_CANCEL_OPTION);
              if(choice==JOptionPane.YES_OPTION){
              fm.delete_employee(x);
              JOptionPane.showMessageDialog(null,"Employee "+str+"deleted successfully");
              }
          }
         
          
         }catch(Exception e){JOptionPane.showMessageDialog(null,"Invalid Input","ERROR",0);}
    }//GEN-LAST:event_okButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GiveLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
///helow