
package final_project;

import java.util.StringTokenizer;
import javax.swing.JOptionPane;


public class UPDATING_EMPLOYEE extends javax.swing.JPanel {

    /**
     * Creates new form UPDATING_EMPLOYEE
     */
    public UPDATING_EMPLOYEE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        backButton = new javax.swing.JButton();
        giveIdLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        designationLabel = new javax.swing.JLabel();
        designationField = new javax.swing.JTextField();
        salaryLabel = new javax.swing.JLabel();
        salaryField = new javax.swing.JTextField();
        performenceLabel = new javax.swing.JLabel();
        performenceField = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        contactInfoField = new javax.swing.JTextField();
        backGroundLabel = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setMinimumSize(new java.awt.Dimension(1170, 700));
        setOpaque(false);
        setLayout(null);

        backButton.setForeground(new java.awt.Color(255, 51, 204));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton);
        backButton.setBounds(30, 20, 130, 25);

        giveIdLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        giveIdLabel.setForeground(new java.awt.Color(255, 51, 204));
        giveIdLabel.setText("Give employee id home you want to update");
        add(giveIdLabel);
        giveIdLabel.setBounds(390, 120, 360, 20);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        add(idField);
        idField.setBounds(390, 180, 120, 22);

        nameLabel.setForeground(new java.awt.Color(255, 51, 204));
        nameLabel.setText("NAME");
        add(nameLabel);
        nameLabel.setBounds(390, 240, 190, 16);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        add(nameField);
        nameField.setBounds(390, 280, 228, 20);

        designationLabel.setForeground(new java.awt.Color(255, 0, 204));
        designationLabel.setText("DESIGNATION");
        add(designationLabel);
        designationLabel.setBounds(390, 330, 230, 16);
        add(designationField);
        designationField.setBounds(390, 380, 228, 22);

        salaryLabel.setForeground(new java.awt.Color(255, 0, 204));
        salaryLabel.setText("SALARY");
        add(salaryLabel);
        salaryLabel.setBounds(390, 430, 230, 16);
        add(salaryField);
        salaryField.setBounds(390, 480, 228, 22);

        performenceLabel.setForeground(new java.awt.Color(255, 0, 204));
        performenceLabel.setText("PERFORMENCE");
        add(performenceLabel);
        performenceLabel.setBounds(710, 230, 180, 20);
        add(performenceField);
        performenceField.setBounds(710, 280, 178, 22);

        birthdayLabel.setForeground(new java.awt.Color(255, 0, 204));
        birthdayLabel.setText("BIRTH DAY");
        add(birthdayLabel);
        birthdayLabel.setBounds(710, 330, 180, 20);

        dayField.setText("dd");
        dayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayFieldActionPerformed(evt);
            }
        });
        add(dayField);
        dayField.setBounds(710, 380, 50, 22);

        confirmButton.setForeground(new java.awt.Color(255, 0, 204));
        confirmButton.setText("CONFIRM");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton);
        confirmButton.setBounds(740, 550, 150, 25);

        monthField.setText("mm");
        monthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFieldActionPerformed(evt);
            }
        });
        add(monthField);
        monthField.setBounds(770, 380, 50, 22);

        yearField.setText("yy");
        add(yearField);
        yearField.setBounds(829, 380, 60, 22);

        contactLabel.setForeground(new java.awt.Color(255, 0, 204));
        contactLabel.setText("CONTACT INFO");
        add(contactLabel);
        contactLabel.setBounds(710, 430, 180, 16);

        contactInfoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactInfoFieldActionPerformed(evt);
            }
        });
        add(contactInfoField);
        contactInfoField.setBounds(710, 480, 180, 22);

        backGroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image2.jpg"))); // NOI18N
        backGroundLabel.setText("jLabel8");
        add(backGroundLabel);
        backGroundLabel.setBounds(10, 0, 1190, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
                  FileManager fm=new FileManager("EMPLOYEE_LIST.txt");
                  String id=idField.getText();
                  if(id.equals("")){
                      JOptionPane.showMessageDialog(null,"Id can not be empty","Warning",2);
                  }
                  else{
                      try{
                          if(fm.search(Integer.parseInt(id))==-1){
                              JOptionPane.showMessageDialog(null,"This id does not exist","Error",2);
                          }
                          else{
                              nameField.setText(ANEMPLOYEE.name.replace('_', ' '));
                              designationField.setText(ANEMPLOYEE.designation);
                              salaryField.setText(String.valueOf(ANEMPLOYEE.salary));
                              performenceField.setText(ANEMPLOYEE.performence);
                              StringTokenizer stk=new StringTokenizer(ANEMPLOYEE.birthDay,"/");
                              String day=stk.nextToken();
                              String month=stk.nextToken();
                              String year=stk.nextToken();
                              dayField.setText(String.valueOf(day));
                              monthField.setText(month);
                              yearField.setText(year);
                              contactInfoField.setText(ANEMPLOYEE.contactInfo);
                          }
                      }catch(Exception e){
                              JOptionPane.showMessageDialog(null,"Invalid id","Error",0);
                      }
                  }
                  

    }//GEN-LAST:event_idFieldActionPerformed

    private void dayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        HOME_PAGE.home.remove(this);
        HOME_PAGE.home.setContentPane(HOME_PAGE.panel);
        HOME_PAGE.panel.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
       
        
        String designation=designationField.getText();
        String id=idField.getText();
        String salary=salaryField.getText();
        String performence=performenceField.getText();
        String contactInfo=contactInfoField.getText();
        int day=Integer.parseInt(dayField.getText());
        int month=Integer.parseInt(monthField.getText());
        int year=Integer.parseInt(yearField.getText());
        int ara[]={0,31,29,31,30,31,30,31,31,30,31,30,31};
        String birthDay=day+"/"+month+"/"+year;
        if(month<=0||month>12){JOptionPane.showMessageDialog(null,"Invalid date");}
        else if(day<=0||day>ara[month]){JOptionPane.showMessageDialog(null,"Invalid date");}
        else
        try{
        int choice=JOptionPane.showConfirmDialog(null,"Are you sure to update employee with User Id :"+idField.getText(),"Select option",JOptionPane.YES_NO_CANCEL_OPTION);
        if(choice==JOptionPane.YES_OPTION){
        FileManager fm=new FileManager("EMPLOYEE_LIST.txt");
        fm.update_employee(Integer.parseInt(id), designation,Integer.parseInt(salary),performence,birthDay,contactInfo);
        JOptionPane.showMessageDialog(null,"Updation successful");
        }
        
        }catch(Exception e){JOptionPane.showMessageDialog(null,"Invalid Input");}
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void contactInfoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactInfoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactInfoFieldActionPerformed

    private void monthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backGroundLabel;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField contactInfoField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField dayField;
    private javax.swing.JTextField designationField;
    private javax.swing.JLabel designationLabel;
    private javax.swing.JLabel giveIdLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField performenceField;
    private javax.swing.JLabel performenceLabel;
    private javax.swing.JTextField salaryField;
    private javax.swing.JLabel salaryLabel;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
